language: java
sudo: false # faster builds

jdk:
  - oraclejdk8
  
cache:
  directories:
    - $HOME/.m2

install: true

script: "mvn cobertura:cobertura -DskipTests=false -Dcheckstyle.skip=false -Drat.skip=false -Dmaven.javadoc.skip=true"
# "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)